_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
                - 105
            "2":
                - 5
                - 6
                - 53
                - 55
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 31
                - 55
            "4": 3.12.3
            "5": 0.19.11
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
colsample_bytree:
    value: 0.5
eval_metric:
    value: mlogloss
learning_rate:
    value: 0.1
max_depth:
    value: 4
min_child_weight:
    value: 1
n_estimators:
    value: 800
num_class:
    value: 6
subsample:
    value: 0.8
use_label_encoder:
    value: false
